version: "3.9"

services:
  api:
    build: .
    container_name: url_shortener_api
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/url_shortener
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: url_shortener_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
